modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="trolling"
version="1.0.0"
displayName="Trolling"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="killt, MCreator"

[[dependencies.trolling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




